/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.discord.api;

import javax.validation.Valid;

import com.discord.model.Message;
import com.discord.model.ModelApiResponse;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@RestController
@Api(value = "Message", tags = "Message", description = "The message API")
@RequestMapping(path = "/api/v1", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
public class MessageApiController {

    @PostMapping(path = "message/send", consumes = MediaType.APPLICATION_JSON_UTF8_VALUE)
    @ApiOperation(value = "Send message to a discord channel", nickname = "sendMessage", response = ModelApiResponse.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Mensagem adicionada com sucesso", response = ModelApiResponse.class),
        @ApiResponse(code = 404, message = "Not found"),
        @ApiResponse(code = 405, message = "Invalid input") })
    ResponseEntity<ModelApiResponse> sendMessage(@ApiParam(value = "É necessário que o campo mensagem esteja preenchido" ,required=true )  @Valid @RequestBody Message body) {
        return null;
    }

}
